
- name: Perform other small tasks
  hosts: all
  gather_facts: true
  become: true
  become_user: "{{ ansible_user }}"

  tasks:
    - name: add git credentials
      block:
      - name: Add a settings to ~/.gitconfig
        community.general.git_config:
          name: '{{ item.name }}'
          scope: global
          value: '{{ item.value }}'
        with_items:
          - name: user.name
            value: Demetry Pascal
          - name: user.email
            value: qtckpuhdsa@gmail.com
    
    - name: update .bashrc
      lineinfile:
        path: '/home/{{ ansible_user }}/.bashrc'
        line: 'source /home/{{ ansible_user }}/.prompt.sh'


